### ISSUE TITLE
safe_mode is currently enabled

### ISSUE THREAD

**Issue by atlekbai** [aspendigital/docker-octobercms#18]
Can't add any PHP code into a static page. It shows an error "safe_mode is currently enabled". How to disable or fix this problem?

**Comment by petehalverson** [comment]
@atlekbai  [October CMS Safe Mode](https://octobercms.com/docs/setup/configuration#safe-mode) is enabled because `APP_DEBUG` is set to `false` by default.

Try starting the [container with the environment variable](https://github.com/aspendigital/docker-octobercms#october-cms-app-environment-config)  `APP_DEBUG=true`:

```bash
docker run --rm -p80:80 -e APP_DEBUG=true aspendigital/octobercms:build.447
```
